
    - name: Ensure Docker is installed
      command: docker --version
      register: docker_installed
      failed_when: docker_installed.rc != 0
      changed_when: false

    - name: Remove old node-app image if exists
      command: docker image rm node-app
      ignore_errors: yes

    - name: Pull latest node-app image
      command: docker pull {{ image_name }}:latest

    - name: Stop running container (if exists)
      command: docker stop node-app
      ignore_errors: yes

    - name: Remove existing container (if exists)
      command: docker rm node-app
      ignore_errors: yes

    - name: Run new container from updated image
      command: >
        docker run -d
        --name node-app
        -p 80:3000
        --restart always
        -e RDS_HOSTNAME={{ RDS_HOSTNAME }}
        -e RDS_USERNAME={{ RDS_USERNAME }}
        -e RDS_PASSWORD={{ RDS_PASSWORD }}
        -e RDS_PORT={{ RDS_PORT }}
        -e REDIS_HOSTNAME={{ REDIS_HOSTNAME }}
        -e REDIS_PORT={{ REDIS_PORT }}
        {{ image_name }}:latest
