---
# tasks file for node-app

- name: update ubuntu server
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add ubuntu user to Docker group
  user:
    name: ubuntu
    group: docker
    append: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
