---
# tasks file for node-app

- name: update ubuntu server
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Add ubuntu user to Docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
